### ISSUE TITLE
System.Data.SqlClient is must have for chart now?

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms-datavisualization#18]
Hi. We have ported our WinForms app from .net 4.7 to .Net Core 3.0, and have following issue.
Chart now want an System.Data.SqlClient.dll.

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Data.SqlClient, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Windows.Forms.DataVisualization.Charting.ChartImage.DataBind()
   at System.Windows.Forms.DataVisualization.Charting.ChartPicture.Paint(Graphics graph, Boolean paintTopLevelElementOnly)
   at System.Windows.Forms.DataVisualization.Charting.Chart.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
In original (.net) version of the project  we have no reference to System.Data.SqlClient, moreover this dll is not loaded when program is running, see screenshot below.
![Snipaste_2019-06-09_11-48-08](https://user-images.githubusercontent.com/17767561/59157217-911cbb80-8aaf-11e9-823a-121048fa3dcd.jpg)
Is it intended behavior?

.Net Core: 3.0.0-preview5.19224.8
System.Windows.Forms.DataVisualization: 1.0.0-prerelease.19218.1
VS 2019 16.1.2
Win 7 pro sp1 x64

**Comment by KlausLoeffelmann** [comment]
Hey @kirsan31,

take a look at the references of the sample app how it's done there:

https://github.com/dotnet/winforms-datavisualization/blob/4bf86692be8bd4b176d37ab12621aa53d5cbf70f/sample/ChartSamples/ChartSamples.csproj#L26

Klaus

**Comment by kirsan31** [comment]
Yea I see. So it's **must have** now for System.Windows.Forms.DataVisualization? If so,may be include it in dependencies?

**Comment by KlausLoeffelmann** [comment]
Well, we need to discuss this if there is additional work to do, also because of this, so I can't give you a final answer right now. Thanks for kicking this off, btw!

https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/

@merriemcgaw, @zsd4yr let's discuss this in an upcoming meeting? 
Maybe @RussKie can also take a look?

**Comment by kirsan31** [comment]
> https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/

Yes, I saw this article.

> so I can't give you a final answer right now. Thanks for kicking this off, btw!

Thank you, so I leave this open for now...

**Comment by halgab** [comment]
Hi. The problem is still here in the latest version of the package available on nuget. Is there any plan to fix it in the coming months?
Thanks

**Comment by kirsan31** [comment]
Yes, the problem is still exists. But I have solved it radicali: https://github.com/kirsan31/winforms-datavisualization/commit/91a639e3056c88e509f6067bade4e8f7b547715e

**Comment by danlyons-softek** [comment]
Could [Chart.cs](https://github.com/dotnet/winforms-datavisualization/blob/master/src/System.Windows.Forms.DataVisualization/General/Chart.cs) use the underlying ADO.NET types instead?

It seems to build OK using [DbDataReader](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdatareader), [DbCommand](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbcommand), and [DbDataReader](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdatareader).  _I'd have gone with the interfaces instead, but there was one spot that needed a reader that implements IEnumerable._

That would let you drop the System.Data.SqlClient dependency while also supporting binds to command and data adapter types from any other library that extends ADO.NET Types (e.g., [ODP.NET](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/), [Npgsql](https://www.nuget.org/packages/Npgsql), [MySql.Data](https://www.nuget.org/packages/MySql.Data), etc.).

That said, my uses of this library do not involve binding to ADO.NET objects, so I haven't tested it beyond being able to load the binary without System.Data.SqlClient around.
