### ISSUE TITLE
Multitargeting for NuGet Package

### ISSUE THREAD

**Issue by dag23** [dotnet/winforms-datavisualization#22]
Currently the NuGet package only has target framework netcoreapp3.0.

I think the package should have multitargeting with .Net Framework, as it is done in the package System.Data.DataSetExtensions.

**Comment by weltkante** [comment]
(Just a heads up, this is a read-only repository as the front page states, so in case nobody should monitor the issues created here you might want to ask on the WinForms repo to get someones attention.)

**Comment by RussKie** [comment]
@dag23 System.Windows.Forms.DataVisualization.dll is an integral part of .NET Framework, so it is unclear to me why you think the project should be multi-targeted.

We have deprecated the project, and we will not be supporting it going forward. It has been open sourced for the community benefit.
If your code depends on this project, you are welcome to fork it and maintain it in a way you see fit (obviously complying with the [license](https://github.com/dotnet/winforms-datavisualization/blob/master/LICENSE.TXT)).
