### ISSUE TITLE
Unable to use the Chart.SaveImage method in a MVC Core web project

### ISSUE THREAD

**Issue by sle1306** [dotnet/winforms-datavisualization#25]
Hello,

I use the Chart class in a web API to generate png charts but the SaveImage requires a reference to the System.Windows.Forms.Control class, which is impossible to reference in a .net Core 3 web api project.

            using (MemoryStream ms = new MemoryStream())
            {
                chart.SaveImage(ms, ChartImageFormat.Png);
                return ms.ToArray();
            }

Error	CS0012	The type 'Control' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

Is there a workaround ?

**Comment by RussKie** [comment]
This repository is effectively deprecated, and out of support.

You're welcome to fork it and tweak it to your needs, including dropping references to System.Windows.Forms. However given this is "winforms-datavisualization" it may not be simple.

**Comment by Dunge** [comment]
Stumbled on the same issue.
You CAN reference the WindowsForms framework by adding this in your csproj:

```
  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />
  </ItemGroup>
```

And everything build, it even execute correctly and I managed to get a valid byte array as a result after calling SaveImage. But for some reason the thread freeze at the end after `return new FileContentResult(outBytes, "image/png");`, the web browser never receive the reply. Without calling classes inside the WindowsForm namespace, the thread doesn't freeze.
