### ISSUE TITLE
Are there any plans to upgrade to .Net 5.0?

### ISSUE THREAD

**Issue by maikebing** [dotnet/winforms-datavisualization#37]

**Comment by wangyugui** [comment]
'We consider the System.Windows.Forms.DataVisualization deprecated',  
and then what is the recommanded solution for the charting of  windows form on .net 5.0 or later?

**Comment by kirsan31** [comment]
@wangyugui 
> 'We consider the System.Windows.Forms.DataVisualization deprecated',
> and then what is the recommanded solution for the charting of windows form on .net 5.0 or later?

See https://github.com/dotnet/winforms-datavisualization/issues/9.

**Comment by RussKie** [comment]
This code in this repo is provided as is for reference and migration purposes, and no further work is planed.

You're welcome to fork the code and migrate it to .NET 5.0 to unblock your projects. You're also welcome to post the link to your fork anyone else who may be interested in this migration.

**Comment by AngeloCresta** [comment]
I've made a rough porting of the projects to .Net 5 (windows).

you'll find it here:
[https://github.com/AngeloCresta/winforms-datavisualization-net5]

Hope it helps
Angelo
