### ISSUE TITLE
DataVisualization: Port accessibility fixes from framework runtime to core runtime

### ISSUE THREAD

**Issue by M-Lipin** [dotnet/winforms-datavisualization#7]

**Comment by M-Lipin** [comment]
Ported the changes related to Chart control accessibility fixes (High Contrast theme support by Chart labels, Focus indicator): #6

**Comment by zsd4yr** [comment]
fixed by #6

**Comment by M-Lipin** [comment]
Verified by QA team, no issues have been found.
