### ISSUE TITLE
New replacement for deprecated DataVisualization?

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms-datavisualization#9]
Hi, can you answer on 2 questions pls.

> This repo is read-only. We consider the System.Windows.Forms.DataVisualization deprecated and we only provide it to ease porting to .NET Core 3. We're not going to innovate in this component and subsequently will not accept any PRs.

- If DataVisualization considered deprecated what is replacement for it in .net core and WinForms?
- Will you accept bug fix PRs?

**Comment by OliaG** [comment]
Thanks for the question!  We want to keep parity for Chart control with .NET Framework and changing it in Core will break the compatibility. You can now use the control in Core as it is in the Framework. For more advanced scenarios we encourage developers to check out Power BI ( you'll need a subscription and connection to internet but you'll get a lot of advanced analytics, so what's best for you really depends on your scenario). And we open sourced the code so you can fork it and improve it to your own taste.

**Comment by kirsan31** [comment]
@OliaG 

> We want to keep parity for Chart control with .NET Framework and changing it in Core will break the compatibility.

Why such decision only about DataVisualization? And how about all other WinForms controls?
As I understand, whole idea of migrating to .net core is that we don't want parity (we want more features in core in the future). Because .net is in maintenance state now...

Power BI is a completely different tool for another tasks ...

Thanks for the answer any way :(

**Comment by OliaG** [comment]
Thanks for your comment! Right now we have a lot of critical tasks like WinForms designer, etc. that is  higher priority. But it's good to hear the feedback and learn how popular this control is.

**Comment by VosWouter87** [comment]
@OliaG It's confusing that the new namespace apparently has the same name as the old one.
When I search this namespace on apisof.net it only shows the .NET Framework variant:
https://apisof.net/catalog/System.Windows.Forms.DataVisualization.Charting
Is this innacurate?
